apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: app
  # type: LoadBalancer
status:
  loadBalancer: {}
