runtime: php

## AE Flex
env: flex
runtime_config:
  document_root: public

skip_files:
  - .env

# # AE Standard
# handlers:
# - url: /(.*\.(gif|png|jpg|css|js|otf|ttf|woff|svg))$
#   static_files: public/\1
#   upload: public/.*\.(gif|png|jpg|css|js|otf|ttf|woff|svg)$
#
# - url: /.*
#   secure: always
#   redirect_http_response_code: 301
#   script: auto

env_variables:
  ## App config
  APP_KEY: base64:N8fUKzisA3znUKJwfGqV5bheZAqZbFYSaZB6KnEJgtI=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  # BROADCAST_DRIVER: log
  LOG_CHANNEL: stderr
  CACHE_DRIVER: database
  # CACHE_DRIVER: file
  # SESSION_DRIVER: database
  SESSION_DRIVER: cookie
  # SESSION_DRIVER: files
  # QUEUE_CONNECTION: sync
  # SESSION_LIFETIME: 120
  # APP_SERVICES_CACHE: /tmp/services.php
  # APP_PACKAGES_CACHE: /tmp/packages.php
  # APP_CONFIG_CACHE: /tmp/config.php
  # APP_ROUTES_CACHE: /tmp/routes.php
  ## DB
  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_DATABASE: laravel
  DB_USERNAME: root
  DB_PASSWORD: S0itg0es1
  DB_SOCKET: /cloudsql/waymo-digital-events:us-central1:waymo-v2
  # ## redis
  REDIS_HOST: 127.0.0.1
  REDIS_PASSWORD: null
  REDIS_PORT: 6379
  ## mailer
  MAIL_MAILER: smtp
  MAIL_HOST: smtp.mailtrap.io
  MAIL_PORT: 2525
  MAIL_USERNAME: null
  MAIL_PASSWORD: null
  MAIL_ENCRYPTION: null
  MAIL_FROM_ADDRESS: null
  MAIL_FROM_NAME: "${APP_NAME}"
  ## pusher
  # PUSHER_APP_ID=
  # PUSHER_APP_KEY=
  # PUSHER_APP_SECRET=
  # PUSHER_APP_CLUSTER=mt1
  # MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
  # MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

beta_settings:
    # for Cloud SQL, set this value to the Cloud SQL connection name,
    # e.g. "project:region:cloudsql-instance"
    cloud_sql_instances: waymo-digital-events:us-central1:waymo-v2
