steps:
  - name: 'gcr.io/$PROJECT_ID/composer'
    args: ['install']
  - name: 'gcr.io/$PROJECT_ID/composer'
    args: ['remove', '--dev', 'facade/ignition']
  - name: gcr.io/cloud-builders/gcloud
    args: ['app', 'deploy', '-q']
